### ISSUE TITLE
how to generate the "cp.npy"

### ISSUE THREAD

**Issue by tranorrepository** [1900zyh/3D-Human-Body-Shape#1]

**Comment by 1900zyh** [comment]
control point  is set manually, so I didn't put all data here.
Now I have updated the codes and the relevant data.
It works now.

**Comment by KIRANKUMAR886** [comment]
where can I find the Train_data

**Comment by boram0603** [comment]
Thank you for your source code.
I have a question.
I want change the control point. Is it possible.
and I want re training. But there is no body_control_points.txt, cp.py and TrainingData folder.
Can I get the file?
Thank you for your effort.

**Comment by 1900zyh** [comment]
Hi @boram0603 ,

We use the training dataset of [SPRING](https://graphics.soe.ucsc.edu/data/BodyModels/index.html), and the body_control_points.txt is generated by manually according to a anthropometric measurement guidance.  We are planing to release relevant data these days. 

Thanks,
Yanhong.

**Comment by boram0603** [comment]
Thank you for your response, I really appreciate your response.
And I have a question again.
These days, I training the source code by body_utils.py, But there is no body_part.obj file.
Could you upload the file?
Sorry to bother you.
Thank you

**Comment by 1900zyh** [comment]
Hi @boram0603 ,
It's my fault, I forgot upload body_part.obj.
Thank you for your kind reminder, now I have uploaded it.
