### ISSUE TITLE
segmentation of human body

### ISSUE THREAD

**Issue by sandhyalaxmiK** [1900zyh/3D-Human-Body-Shape#10]
Hi,
I am running the code successfully and i understand the concept.
I want to segments the r obj obtained.i.e, giving colors to each, for face, hands, legs, body,etc., how to do that. and also how to obtain particular vertices and faces of a specific body part.
By knowing this i can do furthor process. Thank you...

**Comment by 1900zyh** [comment]
hi @sandhyalaxmiK , 

thank you for your interest. 
1. I'm not sure how to assign color info to vertices. It seems that you can directly assign color info by adding three number after three coordinate number in each line for each vertices. 
2. Maybe some 3D viewer can help you to find the coordinate info of some specific vertices. 

Thanks,
