### ISSUE TITLE
convert the output into input

### ISSUE THREAD

**Issue by kaicchenintel** [1900zyh/3D-Human-Body-Shape#15]
If the input is a 3D obj file,   Could you give the measurments of the human body? thanks

**Comment by 1900zyh** [comment]
hi @kaicchenintel , you can get the measurements given a 3D obj file. 
The code can be found here: https://github.com/1900zyh/3D-Human-Body-Shape/blob/master/src/reshaper.py#L58
You need to modify it to fit your requirements. 

And you need to provide the same format of obj file with ours (e.g, human body with 12500 vertices )

**Comment by madhuvaani** [comment]
@1900zyh Hi, I was using that code to get measurements from obj file. Im not sure how to call those functions. Can you help me with the steps? 
And is it possible to get measurements of all parts?

**Comment by 1900zyh** [comment]
@madhuvaani please refer to convert_measure function in [body_util.py](https://github.com/1900zyh/3D-Human-Body-Shape/blob/master/src/body_utils.py)
And you could get measurements only from the obj files with the same specification as the body shape datasets we used. You could get 19 measurements 
including:
M_STR = ["weight", "height", "neck", "chest",
         "belly_button_waist", "gluteal_hip",
         "neck_shoulder_elbow_wirst", "croth_knee_floor",
         "across_back_shoulder_neck", "neck_to_gluteal_hip",
         "natural_waist", "maximum_hip", "natural_waist_rise",
         "shoulder_to_midhand", "mid_upper_arm", "wrist",
         "outer_natural_waist_to_floor", "knee", "maximum_thigh"]

**Comment by farazBhatti** [comment]
Hi @1900zyh , ive trying to figure out how to get anthropometric measurement using obj file. Can you help me in this regard? Also there is no file  "body_utils.py"
