### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by jerrychan1996** [1900zyh/3D-Human-Body-Shape#16]
hi, I m trying to use your code but it always occurs the following error.
![image](https://user-images.githubusercontent.com/49363029/55682027-fb09cf00-595f-11e9-81c9-68d2576d7382.png)
![image](https://user-images.githubusercontent.com/49363029/55682074-bdf20c80-5960-11e9-94e0-bf2d8529a49d.png)
It seems unable to create this file cp.npy. Is there something wrong with my directory?
looking forward to your reply.

**Comment by 1900zyh** [comment]
Hi @jerrychan1996 sorry for the late response.
You can find the cp.npy in the data folder actually. 
And according to the error message, you need to set 'TrainingData' to 'data' .

**Comment by jerrychan1996** [comment]
thank you so much, I will try.
