### ISSUE TITLE
Clarifications on 19 human body measurement

### ISSUE THREAD

**Issue by tamilselvan-eswaramoorthi** [1900zyh/3D-Human-Body-Shape#17]
Hello there,

Thanks for open-sourcing this research work. 
Can I get some more clarifications for all the 19 measurements that you had given as inputs? 
what does natural waist, maximum hip, natural waist rise mean and gluteal hip?  

Thank you.

**Comment by 1900zyh** [comment]
We manually labeled the measurements according to a human anthropometric measurements guide from the Body Lab as described in the paper. 
However, they seem remove the guide from their home page. 
Sorry about that.
