### ISSUE TITLE
frozen GUI

### ISSUE THREAD

**Issue by khanhha** [1900zyh/3D-Human-Body-Shape#2]
hi, I was able to bring up your app but it's frozen. I couldn't manipulate with any UIs at all.

Here is the steps I set up the environment. 

I created a virtual 3.5.5 environment on anaconda and install the following packages using pip.

Ubuntu 16.04
numpy                    1.14.5    
scipy                       1.1.0  
fancyimpute            0.3.2 
mayavi                    4.6.1 
openpyxl                 2.5.5
PyOpenGL              3.1.0 
pyqt                         4.11.4
vtk                           8.1.1  

There seems to be one conflict in your requirements. As stated on the homepage of [Mayavi](https://docs.enthought.com/mayavi/mayavi/installation.html) just supports PyQt5 in Python3, but the requirements have both Python3, Mayavi and PyQt4. 

Could you provide a bit more detail about the version of the packages (Mayavi and PyQt) you installed?

Thanks

**Comment by 1900zyh** [comment]
@khanhha Sorry for the late response. I have tested it again, it works fine. 
Did you run on Windows? If so, I strongly recommend you use `pip install ` .whl files downloaded from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs)

**Comment by khanhha** [comment]
hi @1900zyh: It works well after I restart my Linux os. Thanks for good work.

**Comment by 1900zyh** [comment]
@khanhha Thank you for your attention :)
