### ISSUE TITLE
Please share size chart

### ISSUE THREAD

**Issue by sangramrajekakade** [1900zyh/3D-Human-Body-Shape#24]
I am confused with max 30 size. how to measure this from inches

**Comment by mohan158** [comment]
How can i change / detect some other part measurements?

**Comment by 1900zyh** [comment]
Hi @mohan158 ,

I recommend referring [issue #23 ](https://github.com/1900zyh/3D-Human-Body-Shape/issues/23).
For other part measurements, you need to define the measurements by a set of points by yourself.
