### ISSUE TITLE
Add additional parameters for reshaping

### ISSUE THREAD

**Issue by dallas94** [1900zyh/3D-Human-Body-Shape#25]
@1900zyh Would it be possible to add additional parameters such as calf, ankle, and forearm?

The model seems to do well but I would like to fine tune some of those parameters

**Comment by 1900zyh** [comment]
Hi @dallas94 ,

It is possible to add additional parameters. You need to define a set of points manually to describe the measurements. 
As for the detailed introduction to the body measurements we used,
I recommend referring [issue #23 ](https://github.com/1900zyh/3D-Human-Body-Shape/issues/23)
