### ISSUE TITLE
predict and measurement mismatch 

### ISSUE THREAD

**Issue by matrices-m** [1900zyh/3D-Human-Body-Shape#26]
input weight 58 ,height 170 , chick predict and then click save the result , weight is 31 and height is 169
![image](https://user-images.githubusercontent.com/18238878/94509305-83f88280-0246-11eb-84ad-f5dc0c9372d1.png)

**Comment by 1900zyh** [comment]
Hi @matrices-m ,

Thank you for your interest. 
The input weight is 58 and the height is 170. As for the output in the console, you need to multiply the weight by 2, after which you will get weight 62 and height 170.

We agree that there still exists a reconstruction error between the input measurements and the measurements get from the reconstructed body.
