### ISSUE TITLE
Need Guidance

### ISSUE THREAD

**Issue by asimniazi63** [1900zyh/3D-Human-Body-Shape#27]
I have a model of vertex count = 6890 and triangle face count = 13776, i am trying to load this data but i figured out i have to manually set body control points. Please also tell me about template.txt file? what is it about and how can I manually set control points? much appreciated.

**Comment by okomenchuk** [comment]
@asimniazi63 Hello Friend! Have you solved this problem? Faced the same ...

**Comment by asimniazi63** [comment]
you need to manually pick vertices around the body part i.e. neck and save them into a file. For this purpose you can use meshlab. You can ignore zyh's template format  and create your own.

**Comment by okomenchuk** [comment]
@asimniazi63 thank you very much for your reply! Can you tell me more about the coefficients in the file (0.25 0.5 0.75), did you somehow count them or skip them?

**Comment by asimniazi63** [comment]
I skipped them but noted only the vertices in my new file. you can only use those vertices for distance measurement.
