### ISSUE TITLE
MICE() is not defined

### ISSUE THREAD

**Issue by ismaeilVLSI** [1900zyh/3D-Human-Body-Shape#3]
Inside the reshaper file function MICE is not defined.
Kindly recheck it once...

**Comment by 1900zyh** [comment]
hi @ismaeilVLSI 
MICE is defined in fancyimpute package for data imputing.
Please install this package first.

**Comment by 1900zyh** [comment]
Hi @ismaeilVLSI 
MICE is defined in fancyimpute package for data imputing.
Please install this package first

**Comment by ismaeilVLSI** [comment]
I have installed the fancyimpute but mice package is not working.
After Changing below combination its working.
from fancyimpute import IterativeImputer 
mice <==> IterativeImputer
mice.complete() <==> IterativeImputer.fit_transform()
Thanks

**Comment by KimYC1223** [comment]
@ismaeilVLSI It's works!! Thanks!!
