### ISSUE TITLE
Running it without GUI

### ISSUE THREAD

**Issue by perseus784** [1900zyh/3D-Human-Body-Shape#5]
Hi,
Great work!

I tried running the GUI using demo.py but it gave me the following error,
`    mlab.triangular_mesh(v[:, 0], v[:, 1], v[:, 2], f)
TypeError: string indices must be integer
`

So, I tried to run it manually using reshaper.py, 
that gives an error message of female_measure.npy not found. It is not found anywhere in the repo too.

Can you please clarify on this and also can you give a sample of the OBJ that is generated using this repo?

EMAIL: ipaar3@gmail.com

**Comment by 1900zyh** [comment]
Hi @perseus784 ,

Thank you for your attention. 
1. The error message won't affect running the demo in fact, the GUI can be ran normally. 
2. I didn't release traning data in this repo, and you can use your own datasets for traning. 
3. An OBJ file generated in this repo is similar like the ones shown [here](https://github.com/1900zyh/3D-Human-Body-Shape/tree/master/pics)

Thanks.

**Comment by perseus784** [comment]
But the gui is not running, it just froze and shuts down. In 4-5 secs. I cannot click any button or anywhere in the app window. I'm running in on ubuntu 16

**Comment by 1900zyh** [comment]
Hi @perseus784 ,
I'm not sure what happened on ubuntu 16, but a similar problem can be found [here](https://github.com/1900zyh/3D-Human-Body-Shape/issues/2)

**Comment by perseus784** [comment]
Okay, I tried it, it dint work for me. Can please post a generated obj file sample in the repo or send it in [email](ipaar3@gmail.com) if possible?. I just want see the quality of the obj file that is generated through it..

**Comment by 1900zyh** [comment]
Hi @perseus784 ,
I have uploaded an example obj file [here](https://github.com/1900zyh/3D-Human-Body-Shape/blob/master/data/test.obj).  Actually, we follow the data speficication of [this dataset](https://graphics.soe.ucsc.edu/data/BodyModels/index.html)
Hope it will help. Thanks.
