### ISSUE TITLE
Problem with Training body_utils.py

### ISSUE THREAD

**Issue by KIRANKUMAR886** [1900zyh/3D-Human-Body-Shape#6]
While running the body_utils.py   It needs some numpy files 

File "body_utils.py", line 535, in train
    vertex = np.load(open(os.path.join(DATA_DIR, "%s_vertex.npy"%label),"rb"))
IOError: [Errno 2] No such file or directory: '/home/administrator/3D-Human-Body-Shape/data/male_vertex.npy'
but, in data folder dosn't have those files.

**Comment by 1900zyh** [comment]
hi @KIRANKUMAR886 
we use the traning data released by [SPRING](https://graphics.soe.ucsc.edu/data/BodyModels/index.html). 

You can use your own tranining data here.

**Comment by KIRANKUMAR886** [comment]
hi @1900zyh 

I downloaded that dataset to train but It's shows some npy files are missed . H ow can I generate those numpy files.

Thanks in advanced

**Comment by KIRANKUMAR886** [comment]
@1900zyh 

In that spring data only obj files are there, how you gave those numpy files to train ?

**Comment by 1900zyh** [comment]
please refer to [obj2npy](https://github.com/1900zyh/3D-Human-Body-Shape/blob/master/src/body_utils.py#L88)
