### ISSUE TITLE
Issue with demo.py

### ISSUE THREAD

**Issue by KIRANKUMAR886** [1900zyh/3D-Human-Body-Shape#7]
mlab.triangular_mesh(v[:, 0], v[:, 1], v[:, 2], f)
TypeError: string indices must be integers, not tuple
Traceback (most recent call last):
  File "demo.py", line 228, in <module>
    show_app()
  File "demo.py", line 222, in show_app
    win = HumanShapeAnalysisDemo()
  File "demo.py", line 23, in __init__
    self.viewer3D = MayaviQWidget(container)
  File "/home/administrator/3D-Human-Body-Shape/src/maya_widget.py", line 72, in __init__
    layout.addWidget(self.ui)
TypeError: QBoxLayout.addWidget(QWidget, int stretch=0, Qt.Alignment alignment=0): argument 1 has unexpected type 'PySide.QtGui.QWidget'
QClipboard: Unable to receive an event from the clipboard manager in a reasonable time
[acerE15:19042] *** Process received signal ***
[acerE15:19042] Signal: Segmentation fault (11)
[acerE15:19042] Signal code: Invalid permissions (2)
[acerE15:19042] Failing at address: 0x5ce183b
[acerE15:19042] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f7d6ea7d390]
[acerE15:19042] [ 1] [0x5ce183b]
[acerE15:19042] *** End of error message ***
Segmentation fault (core dumped)

**Comment by 1900zyh** [comment]
@KIRANKUMAR886 
I'm not sure how this problem happens.
Perhaps you can check the version of the library you installed.

**Comment by KIRANKUMAR886** [comment]
@1900zyh 

Can you tell me which versions are used in that repo,  for requirements libraries.
Thank you

**Comment by 1900zyh** [comment]
They are listed [here](https://github.com/1900zyh/3D-Human-Body-Shape/blob/master/requirements.txt)
